Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()
main1
main2
main3
main4
main5
main6
main7
main8
main9
main10
main11
main12
main13
main14
main15
main16
main17
main18
main19
main20
End Sub

Sub main1()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.031920, 0.045586, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031415, 0.044266, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.030420, 0.041659, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.028919, 0.037855, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.026948, 0.032950, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.024568, 0.027055, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.021806, 0.020337, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.018664, 0.013010, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.015126, 0.005317, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.011194, -0.002491, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.006872, -0.010158, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.002185, -0.017438, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.002783, -0.024130, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.007882, -0.030088, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.012934, -0.035201, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.017730, -0.039404, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.022046, -0.042667, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.025866, -0.044847, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.028892, -0.046033, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.031920, -0.045586, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.032315, -0.043636, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.031582, -0.040845, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.030016, -0.037087, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.027637, -0.032467, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.024529, -0.027082, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.020746, -0.021080, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.016346, -0.014633, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.011359, -0.007955, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.005905, -0.001212, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.000161, 0.005459, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.005636, 0.011962, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.011255, 0.018198, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.016465, 0.024077, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.021068, 0.029506, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.024918, 0.034371, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.027915, 0.038558, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.030012, 0.041944, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031279, 0.044362, 0.080000)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane1 As Object
Set myRefPlane1 = Part.FeatureManager.InsertRefPlane(8, 0.080000, 0, 0, 0, 0)
myRefPlane1.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main2()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.030316, 0.045823, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.029853, 0.044507, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.028938, 0.041908, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.027555, 0.038115, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.025738, 0.033222, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.023543, 0.027342, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.020992, 0.020640, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.018082, 0.013326, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.014790, 0.005642, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.011112, -0.002167, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.007047, -0.009847, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.002611, -0.017154, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.002118, -0.023888, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.006995, -0.029901, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.011849, -0.035078, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.016472, -0.039352, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.020647, -0.042685, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.024361, -0.044936, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.027317, -0.046185, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.030316, -0.045823, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.030757, -0.043909, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.030106, -0.041135, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.028658, -0.037385, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.026431, -0.032763, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.023503, -0.027368, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.019926, -0.021345, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.015752, -0.014868, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.011003, -0.008147, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.005796, -0.001350, 0.096621)
boolstatus = Part.InsertCurveFilePoint(-0.000301, 0.005384, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.005251, 0.011953, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.010634, 0.018254, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.015623, 0.024192, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.020024, 0.029670, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.023697, 0.034572, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.026546, 0.038782, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.028528, 0.042179, 0.096621)
boolstatus = Part.InsertCurveFilePoint(0.029715, 0.044598, 0.096621)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane2 As Object
Set myRefPlane2 = Part.FeatureManager.InsertRefPlane(8, 0.096621, 0, 0, 0, 0)
myRefPlane2.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main3()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.027594, 0.046599, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.027203, 0.045281, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.026430, 0.042677, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.025255, 0.038875, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.023707, 0.033969, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.021834, 0.028073, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.019652, 0.021350, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.017146, 0.014007, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.014283, 0.006280, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.011046, -0.001588, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.007420, -0.009348, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.003412, -0.016759, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.000912, -0.023620, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.005418, -0.029779, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.009942, -0.035115, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.014284, -0.039549, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.018230, -0.043035, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.021776, -0.045433, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.024624, -0.046808, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.027594, -0.046599, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.028123, -0.044736, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.027618, -0.041974, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.026377, -0.038211, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.024412, -0.033552, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.021794, -0.028096, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.018569, -0.021992, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.014777, -0.015410, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.010432, -0.008561, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.005640, -0.001614, 0.113242)
boolstatus = Part.InsertCurveFilePoint(-0.000560, 0.005285, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.004583, 0.012025, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.009572, 0.018492, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.014193, 0.024583, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.018256, 0.030191, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.021632, 0.035198, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.024229, 0.039483, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.026014, 0.042924, 0.113242)
boolstatus = Part.InsertCurveFilePoint(0.027063, 0.045364, 0.113242)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane3 As Object
Set myRefPlane3 = Part.FeatureManager.InsertRefPlane(8, 0.113242, 0, 0, 0, 0)
myRefPlane3.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main4()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.023315, 0.048126, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.023038, 0.046796, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.022492, 0.044171, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.021649, 0.040333, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.020529, 0.035378, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.019173, 0.029422, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.017580, 0.022627, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.015718, 0.015195, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.013537, 0.007356, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.011000, -0.000652, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.008072, -0.008587, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.004738, -0.016210, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.001048, -0.023317, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.002879, -0.029749, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.006891, -0.035372, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.010797, -0.040093, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.014394, -0.043848, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.017685, -0.046500, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.020375, -0.048087, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.023315, -0.048126, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.023988, -0.046336, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.023719, -0.043576, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.022808, -0.039772, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.021257, -0.035025, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.019131, -0.029442, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.016460, -0.023169, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.013271, -0.016380, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.009560, -0.009283, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.005417, -0.002052, 0.129863)
boolstatus = Part.InsertCurveFilePoint(-0.000987, 0.005155, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.003519, 0.012210, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.007896, 0.018984, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.011941, 0.025358, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.015477, 0.031212, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.018386, 0.036416, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.020589, 0.040847, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.022062, 0.044379, 0.129863)
boolstatus = Part.InsertCurveFilePoint(0.022894, 0.046866, 0.129863)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane4 As Object
Set myRefPlane4 = Part.FeatureManager.InsertRefPlane(8, 0.129863, 0, 0, 0, 0)
myRefPlane4.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main5()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.019672, 0.048913, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.019490, 0.047587, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.019131, 0.044967, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.018562, 0.041135, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.017796, 0.036186, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.016865, 0.030236, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.015758, 0.023445, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.014431, 0.016009, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.012816, 0.008152, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.010863, 0.000103, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.008520, -0.007899, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.005758, -0.015622, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.002609, -0.022863, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.000817, -0.029454, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.004382, -0.035256, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.007905, -0.040164, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.011188, -0.044101, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.014245, -0.046932, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.016783, -0.048675, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.019672, -0.048913, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.020456, -0.047198, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.020378, -0.044466, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.019739, -0.040662, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.018536, -0.035888, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.016823, -0.030253, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.014620, -0.023902, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.011943, -0.017010, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.008774, -0.009777, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.005189, -0.002385, 0.146484)
boolstatus = Part.InsertCurveFilePoint(-0.001320, 0.005003, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.002634, 0.012247, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.006481, 0.019207, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.010027, 0.025750, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.013109, 0.031746, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.015618, 0.037062, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.017485, 0.041569, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.018694, 0.045143, 0.146484)
boolstatus = Part.InsertCurveFilePoint(0.019343, 0.047646, 0.146484)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane5 As Object
Set myRefPlane5 = Part.FeatureManager.InsertRefPlane(8, 0.146484, 0, 0, 0, 0)
myRefPlane5.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main6()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.016394, 0.049406, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.016296, 0.048088, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.016102, 0.045485, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.015775, 0.041674, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.015323, 0.036749, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.014770, 0.030829, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.014095, 0.024068, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.013241, 0.016660, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.012131, 0.008818, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.010699, 0.000766, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.008880, -0.007263, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.006630, -0.015043, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.003970, -0.022371, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.000997, -0.029076, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.002161, -0.035012, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.005333, -0.040065, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.008327, -0.044145, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.011167, -0.047122, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.013561, -0.048995, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.016394, -0.049406, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.017271, -0.047765, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.017361, -0.045067, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.016965, -0.041279, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.016071, -0.036501, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.014727, -0.030843, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.012945, -0.024450, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.010729, -0.017493, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.008049, -0.010172, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.004967, -0.002668, 0.163105)
boolstatus = Part.InsertCurveFilePoint(-0.001607, 0.004850, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.001847, 0.012230, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.005211, 0.019324, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.008306, 0.025989, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.010976, 0.032087, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.013123, 0.037479, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.014687, 0.042035, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.015660, 0.045631, 0.163105)
boolstatus = Part.InsertCurveFilePoint(0.016147, 0.048137, 0.163105)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane6 As Object
Set myRefPlane6 = Part.FeatureManager.InsertRefPlane(8, 0.163105, 0, 0, 0, 0)
myRefPlane6.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main7()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.013818, 0.049463, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013783, 0.048160, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013715, 0.045585, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013574, 0.041814, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013362, 0.036940, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013097, 0.031079, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.012751, 0.024386, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.012261, 0.017044, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.011538, 0.009263, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.010507, 0.001261, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.009094, -0.006737, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.007245, -0.014511, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.004971, -0.021858, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.002359, -0.028606, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.000473, -0.034606, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.003359, -0.039734, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.006117, -0.043897, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.008775, -0.046965, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.011046, -0.048925, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.013818, -0.049463, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.014759, -0.047887, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.014976, -0.045233, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.014765, -0.041482, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.014110, -0.036731, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.013054, -0.031091, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.011600, -0.024707, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.009745, -0.017747, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.007450, -0.010405, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.004769, -0.002864, 0.179726)
boolstatus = Part.InsertCurveFilePoint(-0.001813, 0.004703, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.001241, 0.012140, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.004221, 0.019290, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.006955, 0.026004, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.009298, 0.032140, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.011159, 0.037555, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.012485, 0.042119, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013273, 0.045709, 0.179726)
boolstatus = Part.InsertCurveFilePoint(0.013635, 0.048201, 0.179726)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane7 As Object
Set myRefPlane7 = Part.FeatureManager.InsertRefPlane(8, 0.179726, 0, 0, 0, 0)
myRefPlane7.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main8()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.011789, 0.049260, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011804, 0.047974, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011832, 0.045434, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011832, 0.041712, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011803, 0.036901, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011758, 0.031115, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011665, 0.024505, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011454, 0.017251, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011029, 0.009556, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.010309, 0.001632, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.009212, -0.006304, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.007677, -0.014033, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.005707, -0.021358, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.003382, -0.028106, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.000813, -0.034123, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.001842, -0.039285, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.004406, -0.043490, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.006912, -0.046612, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.009077, -0.048627, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.011789, -0.049260, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.012776, -0.047741, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.013088, -0.045133, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.013018, -0.041428, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.012548, -0.036722, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.011716, -0.031125, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.010519, -0.024779, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.008949, -0.017851, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.006958, -0.010530, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.004594, -0.002999, 0.196347)
boolstatus = Part.InsertCurveFilePoint(-0.001960, 0.004568, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.000774, 0.012010, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.003447, 0.019167, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.005894, 0.025886, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.007976, 0.032020, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.009610, 0.037426, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.010747, 0.041972, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011392, 0.045539, 0.196347)
boolstatus = Part.InsertCurveFilePoint(0.011656, 0.048009, 0.196347)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane8 As Object
Set myRefPlane8 = Part.FeatureManager.InsertRefPlane(8, 0.196347, 0, 0, 0, 0)
myRefPlane8.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main9()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.010087, 0.048912, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010141, 0.047645, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010248, 0.045143, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010364, 0.041475, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010485, 0.036733, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010621, 0.031029, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010734, 0.024512, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010751, 0.017357, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010572, 0.009761, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.010109, 0.001928, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.009275, -0.005926, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.008002, -0.013591, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.006289, -0.020871, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.004207, -0.027593, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.001862, -0.033603, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.000594, -0.038772, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.002990, -0.042996, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.005362, -0.046151, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.007434, -0.048204, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.010087, -0.048912, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.011106, -0.047446, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.011495, -0.044886, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.011541, -0.041232, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.011225, -0.036580, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.010578, -0.031038, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.009596, -0.024747, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.008264, -0.017870, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.006530, -0.010594, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.004434, -0.003099, 0.212968)
boolstatus = Part.InsertCurveFilePoint(-0.002074, 0.004441, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.000390, 0.011860, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.002801, 0.018997, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.005003, 0.025694, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.006865, 0.031804, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.008307, 0.037182, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.009287, 0.041697, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.009811, 0.045233, 0.212968)
boolstatus = Part.InsertCurveFilePoint(0.009994, 0.047676, 0.212968)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane9 As Object
Set myRefPlane9 = Part.FeatureManager.InsertRefPlane(8, 0.212968, 0, 0, 0, 0)
myRefPlane9.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main10()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.008934, 0.048425, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009013, 0.047177, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009170, 0.044712, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009360, 0.041099, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009577, 0.036426, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009829, 0.030807, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.010075, 0.024385, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.010240, 0.017332, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.010220, 0.009840, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009925, 0.002110, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.009265, -0.005650, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.008169, -0.013232, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.006630, -0.020444, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.004717, -0.027114, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.002529, -0.033087, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.000215, -0.038233, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.002059, -0.042446, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.004333, -0.045605, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.006333, -0.047671, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.008934, -0.048425, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.009969, -0.047001, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.010405, -0.044485, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.010526, -0.040884, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.010310, -0.036291, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.009787, -0.030815, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.008949, -0.024593, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.007777, -0.017786, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.006218, -0.010578, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.004307, -0.003146, 0.229589)
boolstatus = Part.InsertCurveFilePoint(-0.002136, 0.004335, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.000139, 0.011700, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.002369, 0.018784, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.004402, 0.025432, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.006110, 0.031493, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.007421, 0.036824, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.008294, 0.041296, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.008737, 0.044792, 0.229589)
boolstatus = Part.InsertCurveFilePoint(0.008868, 0.047204, 0.229589)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane10 As Object
Set myRefPlane10 = Part.FeatureManager.InsertRefPlane(8, 0.229589, 0, 0, 0, 0)
myRefPlane10.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main11()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.007941, 0.047880, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.008042, 0.046651, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.008240, 0.044226, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.008492, 0.040668, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.008789, 0.036067, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009137, 0.030534, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009495, 0.024210, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009782, 0.017263, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009896, 0.009879, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009743, 0.002256, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.009231, -0.005403, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.008286, -0.012894, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.006898, -0.020029, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.005131, -0.026636, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.003082, -0.032561, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.000893, -0.037673, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.001273, -0.041866, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.003458, -0.045019, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.005392, -0.047091, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.007941, -0.047880, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.008987, -0.046495, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.009461, -0.044023, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.009645, -0.040477, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.009513, -0.035947, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.009096, -0.030541, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.008381, -0.024395, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.007347, -0.017666, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.005939, -0.010535, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.004189, -0.003177, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.002182, 0.004234, 0.246211)
boolstatus = Part.InsertCurveFilePoint(-0.000071, 0.011532, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.002000, 0.018553, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.003885, 0.025140, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.005461, 0.031144, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.006657, 0.036421, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.007437, 0.040843, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.007812, 0.044297, 0.246211)
boolstatus = Part.InsertCurveFilePoint(0.007898, 0.046675, 0.246211)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane11 As Object
Set myRefPlane11 = Part.FeatureManager.InsertRefPlane(8, 0.246211, 0, 0, 0, 0)
myRefPlane11.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main12()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.007110, 0.047278, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007227, 0.046069, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007459, 0.043683, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007760, 0.040183, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.008121, 0.035656, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.008546, 0.030211, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.008992, 0.023987, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.009378, 0.017148, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.009600, 0.009877, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.009563, 0.002367, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.009172, -0.005184, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.008353, -0.012577, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007092, -0.019625, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.005450, -0.026159, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.003520, -0.032025, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.001440, -0.037093, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.000632, -0.041255, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.002736, -0.044393, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.004610, -0.046463, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.007110, -0.047278, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.008160, -0.045929, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.008664, -0.043502, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.008898, -0.040012, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.008836, -0.035548, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.008505, -0.030217, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.007892, -0.024152, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.006974, -0.017510, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.005693, -0.010465, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.004078, -0.003192, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.002212, 0.004138, 0.262832)
boolstatus = Part.InsertCurveFilePoint(-0.000242, 0.011358, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.001694, 0.018304, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.003452, 0.024820, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.004915, 0.030757, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.006015, 0.035972, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.006718, 0.040340, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007036, 0.043747, 0.262832)
boolstatus = Part.InsertCurveFilePoint(0.007085, 0.046091, 0.262832)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane12 As Object
Set myRefPlane12 = Part.FeatureManager.InsertRefPlane(8, 0.262832, 0, 0, 0, 0)
myRefPlane12.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main13()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.006439, 0.046639, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.006568, 0.045450, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.006825, 0.043103, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.007163, 0.039660, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.007572, 0.035207, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.008056, 0.029850, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.008569, 0.023727, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.009031, 0.016997, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.009336, 0.009841, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.009389, 0.002444, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.009094, -0.004996, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.008375, -0.012285, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.007217, -0.019241, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.005678, -0.025694, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.003847, -0.031493, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.001859, -0.036509, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.000131, -0.040631, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.002166, -0.043746, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.003987, -0.045807, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.006439, -0.046639, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.007489, -0.045323, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.008014, -0.042939, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.008285, -0.039505, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.008278, -0.035109, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.008015, -0.029856, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.007484, -0.023877, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.006659, -0.017325, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.005482, -0.010373, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.003978, -0.003191, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.002228, 0.004048, 0.279453)
boolstatus = Part.InsertCurveFilePoint(-0.000373, 0.011181, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.001450, 0.018044, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.003104, 0.024481, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.004474, 0.030344, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.005495, 0.035493, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.006135, 0.039802, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.006408, 0.043161, 0.279453)
boolstatus = Part.InsertCurveFilePoint(0.006428, 0.045470, 0.279453)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve13")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane13 As Object
Set myRefPlane13 = Part.FeatureManager.InsertRefPlane(8, 0.279453, 0, 0, 0, 0)
myRefPlane13.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve13", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main14()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.005823, 0.045999, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005964, 0.044830, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.006243, 0.042522, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.006614, 0.039135, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.007066, 0.034754, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.007602, 0.029484, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.008175, 0.023460, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.008705, 0.016838, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.009084, 0.009794, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.009218, 0.002511, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.009010, -0.004819, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.008383, -0.012005, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.007320, -0.018867, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005876, -0.025239, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.004137, -0.030970, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.002236, -0.035931, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.000321, -0.040013, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.001648, -0.043103, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.003418, -0.045152, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.005823, -0.045999, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.006872, -0.044715, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.007415, -0.042373, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.007721, -0.038995, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.007762, -0.034666, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.007562, -0.029489, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.007105, -0.023596, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.006366, -0.017135, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.005283, -0.010275, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.003882, -0.003187, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.002239, 0.003962, 0.296074)
boolstatus = Part.InsertCurveFilePoint(-0.000491, 0.011006, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.001228, 0.017785, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.002785, 0.024142, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.004069, 0.029931, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005018, 0.035013, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005601, 0.039263, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005832, 0.042574, 0.296074)
boolstatus = Part.InsertCurveFilePoint(0.005826, 0.044848, 0.296074)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve14")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane14 As Object
Set myRefPlane14 = Part.FeatureManager.InsertRefPlane(8, 0.296074, 0, 0, 0, 0)
myRefPlane14.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve14", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main15()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.005290, 0.045364, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.005440, 0.044214, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.005737, 0.041943, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.006135, 0.038610, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.006624, 0.034299, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.007202, 0.029114, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.007825, 0.023186, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.008411, 0.016670, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.008853, 0.009735, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.009055, 0.002563, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.008922, -0.004659, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.008373, -0.011744, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.007393, -0.018513, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.006032, -0.024803, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.004375, -0.030464, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.002550, -0.035369, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.000704, -0.039408, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.001206, -0.042471, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.002930, -0.044507, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.005290, -0.045364, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.006336, -0.044109, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.006894, -0.041808, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.007227, -0.038483, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.007310, -0.034219, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.007163, -0.029119, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.006770, -0.023310, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.006104, -0.016938, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.005104, -0.010172, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.003793, -0.003176, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.002243, 0.003880, 0.312695)
boolstatus = Part.InsertCurveFilePoint(-0.000590, 0.010836, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.001037, 0.017529, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.002510, 0.023806, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.003719, 0.029521, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.004603, 0.034535, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.005136, 0.038727, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.005332, 0.041990, 0.312695)
boolstatus = Part.InsertCurveFilePoint(0.005304, 0.044230, 0.312695)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve15")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane15 As Object
Set myRefPlane15 = Part.FeatureManager.InsertRefPlane(8, 0.312695, 0, 0, 0, 0)
myRefPlane15.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve15", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main16()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.004823, 0.044694, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004981, 0.043564, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.005292, 0.041331, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.005712, 0.038055, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.006229, 0.033816, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.006842, 0.028717, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.007506, 0.022888, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.008137, 0.016478, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.008631, 0.009656, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.008891, 0.002599, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.008821, -0.004510, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.008341, -0.011488, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.007433, -0.018159, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.006147, -0.024361, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004564, -0.029948, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.002809, -0.034791, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.001026, -0.038782, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.000828, -0.041813, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.002507, -0.043831, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.004823, -0.044694, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.005863, -0.043469, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.006431, -0.041208, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.006788, -0.037939, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.006905, -0.033743, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.006804, -0.028721, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.006466, -0.023000, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.005865, -0.016724, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.004938, -0.010055, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.003706, -0.003159, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.002241, 0.003800, 0.329316)
boolstatus = Part.InsertCurveFilePoint(-0.000673, 0.010660, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.000873, 0.017262, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.002269, 0.023453, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.003410, 0.029087, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004239, 0.034030, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004728, 0.038161, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004893, 0.041374, 0.329316)
boolstatus = Part.InsertCurveFilePoint(0.004847, 0.043578, 0.329316)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve16")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane16 As Object
Set myRefPlane16 = Part.FeatureManager.InsertRefPlane(8, 0.329316, 0, 0, 0, 0)
myRefPlane16.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve16", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main17()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.004387, 0.044012, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004551, 0.042901, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004875, 0.040707, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.005315, 0.037487, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.005857, 0.033320, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.006501, 0.028309, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.007201, 0.022579, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.007874, 0.016278, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.008415, 0.009570, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.008727, 0.002628, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.008714, -0.004367, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.008299, -0.011236, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.007459, -0.017806, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.006243, -0.023919, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004731, -0.029428, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.003043, -0.034207, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.001321, -0.038148, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.000479, -0.041145, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.002115, -0.043144, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.004387, -0.044012, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.005419, -0.042815, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.005997, -0.040595, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.006374, -0.037381, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.006523, -0.033254, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.006463, -0.028313, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.006177, -0.022681, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.005636, -0.016501, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.004777, -0.009932, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.003621, -0.003137, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.002235, 0.003721, 0.345937)
boolstatus = Part.InsertCurveFilePoint(-0.000748, 0.010483, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.000720, 0.016991, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.002044, 0.023093, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.003122, 0.028646, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.003897, 0.033515, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004345, 0.037583, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004482, 0.040746, 0.345937)
boolstatus = Part.InsertCurveFilePoint(0.004419, 0.042914, 0.345937)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve17")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane17 As Object
Set myRefPlane17 = Part.FeatureManager.InsertRefPlane(8, 0.345937, 0, 0, 0, 0)
myRefPlane17.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve17", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main18()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.003996, 0.043319, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004165, 0.042228, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004500, 0.040072, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004956, 0.036908, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.005520, 0.032814, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.006189, 0.027890, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.006919, 0.022259, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.007626, 0.016067, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.008207, 0.009473, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.008564, 0.002648, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.008603, -0.004232, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.008243, -0.010991, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.007465, -0.017459, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.006314, -0.023480, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004866, -0.028909, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.003240, -0.033622, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.001575, -0.037510, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.000173, -0.040471, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.001768, -0.042449, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.003996, -0.043319, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.005020, -0.042149, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.005604, -0.039970, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.005998, -0.036812, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.006175, -0.032753, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.006152, -0.027893, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.005911, -0.022352, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.005424, -0.016270, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.004627, -0.009803, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.003539, -0.003112, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.002225, 0.003644, 0.362558)
boolstatus = Part.InsertCurveFilePoint(-0.000811, 0.010305, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.000585, 0.016716, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.001843, 0.022727, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.002863, 0.028196, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.003590, 0.032992, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004002, 0.036996, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004113, 0.040107, 0.362558)
boolstatus = Part.InsertCurveFilePoint(0.004035, 0.042240, 0.362558)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve18")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane18 As Object
Set myRefPlane18 = Part.FeatureManager.InsertRefPlane(8, 0.362558, 0, 0, 0, 0)
myRefPlane18.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve18", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main19()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.003773, 0.042629, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003943, 0.041556, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004280, 0.039436, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004740, 0.036325, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.005310, 0.032300, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.005987, 0.027458, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.006725, 0.021922, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.007443, 0.015833, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008038, 0.009349, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008415, 0.002636, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008478, -0.004132, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008149, -0.010782, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.007407, -0.017147, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.006297, -0.023075, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004892, -0.028421, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003310, -0.033063, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.001687, -0.036894, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.000023, -0.039813, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.001584, -0.041764, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.003773, -0.042629, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.004784, -0.041481, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005367, -0.039340, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005766, -0.036235, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005955, -0.032243, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005950, -0.027462, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005733, -0.022010, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005276, -0.016025, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.004516, -0.009661, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.003470, -0.003074, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.002202, 0.003576, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.000836, 0.010134, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.000515, 0.016446, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.001730, 0.022364, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.002713, 0.027748, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003411, 0.032468, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003801, 0.036408, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003899, 0.039470, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003815, 0.041567, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003773, 0.042629, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003773, 0.042629, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003943, 0.041556, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004280, 0.039436, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004740, 0.036325, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.005310, 0.032300, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.005987, 0.027458, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.006725, 0.021922, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.007443, 0.015833, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008038, 0.009349, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008415, 0.002636, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008478, -0.004132, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.008149, -0.010782, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.007407, -0.017147, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.006297, -0.023075, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.004892, -0.028421, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003310, -0.033063, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.001687, -0.036894, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.000023, -0.039813, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.001584, -0.041764, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.003773, -0.042629, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.004784, -0.041481, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005367, -0.039340, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005766, -0.036235, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005955, -0.032243, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005950, -0.027462, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005733, -0.022010, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.005276, -0.016025, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.004516, -0.009661, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.003470, -0.003074, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.002202, 0.003576, 0.379179)
boolstatus = Part.InsertCurveFilePoint(-0.000836, 0.010134, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.000515, 0.016446, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.001730, 0.022364, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.002713, 0.027748, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003411, 0.032468, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003801, 0.036408, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003899, 0.039470, 0.379179)
boolstatus = Part.InsertCurveFilePoint(0.003815, 0.041567, 0.379179)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve19")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane19 As Object
Set myRefPlane19 = Part.FeatureManager.InsertRefPlane(8, 0.379179, 0, 0, 0, 0)
myRefPlane19.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve19", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main20()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.003669, 0.041940, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003838, 0.040884, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004172, 0.038800, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004627, 0.035740, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005192, 0.031781, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005862, 0.027018, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006594, 0.021573, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007307, 0.015583, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007899, 0.009205, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008276, 0.002602, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008344, -0.004056, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008027, -0.010598, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007304, -0.016862, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006217, -0.022693, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004841, -0.027955, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003289, -0.032523, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.001696, -0.036293, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.000017, -0.039166, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.001517, -0.041087, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.003669, -0.041940, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.004666, -0.040812, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005241, -0.038706, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005637, -0.035652, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005826, -0.031725, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005826, -0.027021, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005618, -0.021658, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005174, -0.015770, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.004433, -0.009508, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.003410, -0.003028, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.002170, 0.003516, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.000832, 0.009969, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.000490, 0.016180, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.001680, 0.022003, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.002642, 0.027300, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003324, 0.031944, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003704, 0.035821, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003797, 0.038832, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003712, 0.040895, 0.395800)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve20")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane20 As Object
Set myRefPlane20 = Part.FeatureManager.InsertRefPlane(8, 0.395800, 0, 0, 0, 0)
myRefPlane20.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve20", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

