Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()
main1
main2
main3
main4
main5
main6
main7
main8
main9
main10
End Sub

Sub main1()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.031920, 0.045586, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031695, 0.044998, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031249, 0.043831, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.030586, 0.042094, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.029706, 0.039814, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.028589, 0.037036, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.027277, 0.033769, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.025784, 0.030050, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.024111, 0.025930, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.022270, 0.021458, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.020263, 0.016696, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.018084, 0.011717, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.015730, 0.006593, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.013199, 0.001400, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.010492, -0.003786, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.007614, -0.008892, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.004573, -0.013844, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.001384, -0.018576, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.001927, -0.023030, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.005311, -0.027166, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.008707, -0.030955, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.012053, -0.034373, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.015281, -0.037404, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.018423, -0.039968, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.021296, -0.042143, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.023957, -0.043839, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.026343, -0.045066, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.028330, -0.045875, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.029941, -0.046227, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.031920, -0.045586, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.032209, -0.044639, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.032259, -0.043124, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.031747, -0.041281, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.030881, -0.038992, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.029651, -0.036292, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.028060, -0.033221, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.026141, -0.029800, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.023912, -0.026069, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.021392, -0.022073, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.018591, -0.017867, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.015527, -0.013508, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.012211, -0.009057, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.008670, -0.004572, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.004954, -0.000091, 0.080000)
boolstatus = Part.InsertCurveFilePoint(-0.001129, 0.004351, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.002737, 0.008726, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.006574, 0.013004, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.010316, 0.017156, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.013894, 0.021156, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.017243, 0.024977, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.020311, 0.028590, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.023063, 0.031955, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.025442, 0.035054, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.027429, 0.037849, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.029076, 0.040255, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.030224, 0.042348, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031067, 0.043958, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031634, 0.045041, 0.080000)
boolstatus = Part.InsertCurveFilePoint(0.031927, 0.045581, 0.080000)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane1 As Object
Set myRefPlane1 = Part.FeatureManager.InsertRefPlane(8, 0.080000, 0, 0, 0, 0)
myRefPlane1.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main2()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.027119, 0.046768, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.026950, 0.046181, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.026615, 0.045014, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.026117, 0.043278, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.025455, 0.040999, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.024604, 0.038217, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.023604, 0.034946, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.022467, 0.031223, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.021189, 0.027096, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.019778, 0.022614, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.018230, 0.017840, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.016534, 0.012839, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.014680, 0.007685, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.012660, 0.002449, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.010469, -0.002795, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.008106, -0.007976, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.005574, -0.013022, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.002879, -0.017866, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.000043, -0.022451, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.002890, -0.026735, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.005863, -0.030683, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.008818, -0.034269, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.011692, -0.037470, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.014521, -0.040213, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.017121, -0.042556, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.019557, -0.044418, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.021764, -0.045803, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.023620, -0.046751, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.025151, -0.047225, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.027119, -0.046768, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.027477, -0.045876, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.027651, -0.044413, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.027308, -0.042588, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.026660, -0.040300, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.025693, -0.037585, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.024408, -0.034480, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.022833, -0.031010, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.020985, -0.027214, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.018877, -0.023137, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.016514, -0.018834, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.013909, -0.014361, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.011069, -0.009778, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.008013, -0.005143, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.004788, -0.000499, 0.115089)
boolstatus = Part.InsertCurveFilePoint(-0.001453, 0.004118, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.001926, 0.008673, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.005286, 0.013131, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.008564, 0.017461, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.011696, 0.021628, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.014621, 0.025605, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.017291, 0.029356, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.019676, 0.032841, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.021722, 0.036038, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.023413, 0.038907, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.024809, 0.041373, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.025746, 0.043494, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.026429, 0.045122, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.026888, 0.046218, 0.115089)
boolstatus = Part.InsertCurveFilePoint(0.027126, 0.046764, 0.115089)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane2 As Object
Set myRefPlane2 = Part.FeatureManager.InsertRefPlane(8, 0.115089, 0, 0, 0, 0)
myRefPlane2.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main3()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.018891, 0.049055, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018819, 0.048466, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018676, 0.047293, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018463, 0.045551, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018175, 0.043260, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.017783, 0.040459, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.017323, 0.037165, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.016801, 0.033416, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.016205, 0.029258, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.015535, 0.024739, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.014778, 0.019918, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.013913, 0.014856, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.012921, 0.009623, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.011782, 0.004287, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.010480, -0.001084, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.009003, -0.006419, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.007343, -0.011652, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.005496, -0.016716, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.003473, -0.021552, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.001312, -0.026114, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.000939, -0.030360, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.003229, -0.034255, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.005499, -0.037768, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.007796, -0.040834, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.009935, -0.043481, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.011989, -0.045642, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.013897, -0.047309, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.015534, -0.048503, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.016932, -0.049192, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.018891, -0.049055, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.019371, -0.048253, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.019762, -0.046875, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.019712, -0.045070, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.019439, -0.042773, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.018926, -0.040019, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.018166, -0.036841, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.017185, -0.033268, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.015991, -0.029340, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.014589, -0.025103, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.012979, -0.020610, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.011161, -0.015917, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.009135, -0.011082, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.006908, -0.006164, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.004521, -0.001211, 0.150178)
boolstatus = Part.InsertCurveFilePoint(-0.002025, 0.003732, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.000524, 0.008622, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.003069, 0.013418, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.005554, 0.018076, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.007924, 0.022557, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.010125, 0.026822, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.012116, 0.030832, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.013873, 0.034543, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.015349, 0.037926, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.016534, 0.040940, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.017497, 0.043521, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018073, 0.045701, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018480, 0.047369, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018753, 0.048491, 0.150178)
boolstatus = Part.InsertCurveFilePoint(0.018898, 0.049052, 0.150178)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane3 As Object
Set myRefPlane3 = Part.FeatureManager.InsertRefPlane(8, 0.150178, 0, 0, 0, 0)
myRefPlane3.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main4()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.012959, 0.049482, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012953, 0.048905, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012941, 0.047755, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012924, 0.046047, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012894, 0.043801, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012818, 0.041050, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012730, 0.037815, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012630, 0.034133, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012504, 0.030047, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012345, 0.025605, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012135, 0.020860, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.011847, 0.015873, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.011454, 0.010705, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.010930, 0.005421, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.010252, 0.000086, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.009401, -0.005233, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.008362, -0.010473, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.007124, -0.015570, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.005691, -0.020466, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.004095, -0.025111, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.002378, -0.029461, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.000585, -0.033475, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.001230, -0.037118, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.003120, -0.040332, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.004901, -0.043123, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.006654, -0.045435, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.008318, -0.047253, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.009772, -0.048585, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.011049, -0.049403, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.012959, -0.049482, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.013510, -0.048759, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.014037, -0.047468, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.014184, -0.045717, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.014169, -0.043467, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.013971, -0.040748, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.013580, -0.037592, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.013018, -0.034031, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.012288, -0.030104, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.011391, -0.025855, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.010320, -0.021336, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.009070, -0.016600, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.007634, -0.011705, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.006013, -0.006708, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.004241, -0.001660, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.002362, 0.003390, 0.185267)
boolstatus = Part.InsertCurveFilePoint(-0.000426, 0.008395, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.001515, 0.013307, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.003414, 0.018081, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.005222, 0.022671, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.006889, 0.027034, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.008380, 0.031127, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.009677, 0.034906, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.010738, 0.038337, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.011558, 0.041380, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012210, 0.043980, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012531, 0.046150, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012744, 0.047807, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012887, 0.048922, 0.185267)
boolstatus = Part.InsertCurveFilePoint(0.012966, 0.049480, 0.185267)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane4 As Object
Set myRefPlane4 = Part.FeatureManager.InsertRefPlane(8, 0.185267, 0, 0, 0, 0)
myRefPlane4.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main5()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.009574, 0.048695, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009604, 0.048135, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009661, 0.047022, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009747, 0.045367, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009853, 0.043190, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009945, 0.040521, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010054, 0.037384, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010179, 0.033812, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010302, 0.029848, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010415, 0.025537, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010497, 0.020930, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010518, 0.016082, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010448, 0.011054, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.010258, 0.005906, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009922, 0.000700, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009418, -0.004503, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.008727, -0.009639, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.007834, -0.014649, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.006741, -0.019476, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.005475, -0.024070, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.004074, -0.028385, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.002579, -0.032380, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.001040, -0.036018, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.000597, -0.039243, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.002154, -0.042053, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.003712, -0.044397, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.005215, -0.046258, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.006543, -0.047635, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.007730, -0.048504, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.009574, -0.048695, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010152, -0.048028, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010740, -0.046810, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010987, -0.045123, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.011107, -0.042943, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.011079, -0.040298, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010891, -0.037219, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010560, -0.033737, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.010090, -0.029890, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.009477, -0.025721, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.008711, -0.021281, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.007786, -0.016620, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.006689, -0.011793, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.005420, -0.006857, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.004007, -0.001863, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.002491, 0.003141, 0.220356)
boolstatus = Part.InsertCurveFilePoint(-0.000918, 0.008103, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.000667, 0.012977, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.002219, 0.017714, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.003694, 0.022267, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.005046, 0.026593, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.006243, 0.030646, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.007273, 0.034383, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.008094, 0.037769, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.008705, 0.040765, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009180, 0.043322, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009360, 0.045443, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009467, 0.047060, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009538, 0.048148, 0.220356)
boolstatus = Part.InsertCurveFilePoint(0.009581, 0.048694, 0.220356)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane5 As Object
Set myRefPlane5 = Part.FeatureManager.InsertRefPlane(8, 0.220356, 0, 0, 0, 0)
myRefPlane5.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main6()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.007479, 0.047545, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007528, 0.047004, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007625, 0.045927, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007770, 0.044326, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007952, 0.042220, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008141, 0.039637, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008362, 0.036600, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008615, 0.033143, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008881, 0.029307, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009150, 0.025133, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009399, 0.020671, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009599, 0.015974, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009717, 0.011099, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009723, 0.006103, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009590, 0.001045, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.009294, -0.004015, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008813, -0.009019, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.008133, -0.013907, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007253, -0.018625, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.006195, -0.023124, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.004997, -0.027358, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.003695, -0.031285, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.002339, -0.034867, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.000872, -0.038053, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.000534, -0.040834, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.001957, -0.043163, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.003344, -0.045022, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.004580, -0.046406, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.005699, -0.047291, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.007479, -0.047545, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008064, -0.046919, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008678, -0.045761, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008981, -0.044135, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.009178, -0.042027, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.009248, -0.039463, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.009179, -0.036472, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008988, -0.033085, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008673, -0.029339, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.008234, -0.025277, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.007655, -0.020945, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.006931, -0.016394, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.006046, -0.011676, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.004999, -0.006846, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.003815, -0.001953, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.002531, 0.002951, 0.255444)
boolstatus = Part.InsertCurveFilePoint(-0.001189, 0.007819, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.000167, 0.012601, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.001496, 0.017249, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.002757, 0.021716, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.003907, 0.025958, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.004918, 0.029930, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.005777, 0.033590, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.006448, 0.036901, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.006930, 0.039827, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007296, 0.042323, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007392, 0.044385, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007435, 0.045956, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007465, 0.047014, 0.255444)
boolstatus = Part.InsertCurveFilePoint(0.007486, 0.047544, 0.255444)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane6 As Object
Set myRefPlane6 = Part.FeatureManager.InsertRefPlane(8, 0.255444, 0, 0, 0, 0)
myRefPlane6.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main7()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.006001, 0.046211, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006062, 0.045688, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006184, 0.044648, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006366, 0.043102, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006597, 0.041069, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006847, 0.038574, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.007140, 0.035641, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.007475, 0.032302, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.007832, 0.028595, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.008201, 0.024563, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.008559, 0.020251, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.008874, 0.015710, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.009115, 0.010995, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.009251, 0.006160, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.009254, 0.001261, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.009100, -0.003644, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.008765, -0.008499, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.008234, -0.013248, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.007504, -0.017837, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006598, -0.022219, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.005548, -0.026348, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.004391, -0.030183, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.003172, -0.033684, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.001835, -0.036806, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.000547, -0.039534, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.000770, -0.041826, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.002064, -0.043661, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.003225, -0.045032, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.004284, -0.045919, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.006001, -0.046211, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.006583, -0.045620, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007208, -0.044515, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007543, -0.042950, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007788, -0.040914, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007923, -0.038434, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007934, -0.035538, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007837, -0.032255, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007631, -0.028621, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.007311, -0.024678, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.006864, -0.020471, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.006281, -0.016047, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.005548, -0.011458, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.004660, -0.006756, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.003641, -0.001990, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.002526, 0.002791, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.001354, 0.007537, 0.290533)
boolstatus = Part.InsertCurveFilePoint(-0.000166, 0.012200, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.000999, 0.016733, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.002103, 0.021089, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.003106, 0.025224, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.003981, 0.029095, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.004717, 0.032660, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.005280, 0.035882, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.005670, 0.038727, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.005959, 0.041152, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.005999, 0.043150, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006000, 0.044672, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006000, 0.045696, 0.290533)
boolstatus = Part.InsertCurveFilePoint(0.006007, 0.046210, 0.290533)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane7 As Object
Set myRefPlane7 = Part.FeatureManager.InsertRefPlane(8, 0.290533, 0, 0, 0, 0)
myRefPlane7.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main8()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.004922, 0.044846, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004992, 0.044341, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.005130, 0.043336, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.005335, 0.041844, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.005598, 0.039880, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.005887, 0.037470, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.006228, 0.034636, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.006616, 0.031411, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.007033, 0.027830, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.007467, 0.023933, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.007896, 0.019766, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008288, 0.015377, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008612, 0.010818, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008837, 0.006140, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008934, 0.001398, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008878, -0.003353, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008647, -0.008059, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.008224, -0.012665, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.007606, -0.017122, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.006813, -0.021381, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.005876, -0.025398, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004830, -0.029132, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.003716, -0.032544, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.002482, -0.035592, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.001288, -0.038257, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.000057, -0.040501, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.001161, -0.042302, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.002258, -0.043652, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.003266, -0.044530, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.004922, -0.044846, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.005497, -0.044285, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006123, -0.043227, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006477, -0.041718, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006754, -0.039753, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006932, -0.037355, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006999, -0.034552, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006967, -0.031372, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006837, -0.027851, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006603, -0.024028, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.006251, -0.019947, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.005772, -0.015654, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.005150, -0.011198, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.004381, -0.006629, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.003486, -0.001996, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.002499, 0.002653, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.001455, 0.007269, 0.325622)
boolstatus = Part.InsertCurveFilePoint(-0.000395, 0.011806, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.000646, 0.016216, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.001631, 0.020454, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.002522, 0.024476, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.003295, 0.028240, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.003939, 0.031704, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004423, 0.034834, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004746, 0.037595, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004979, 0.039948, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004979, 0.041883, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004951, 0.043356, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004932, 0.044347, 0.325622)
boolstatus = Part.InsertCurveFilePoint(0.004928, 0.044845, 0.325622)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane8 As Object
Set myRefPlane8 = Part.FeatureManager.InsertRefPlane(8, 0.325622, 0, 0, 0, 0)
myRefPlane8.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main9()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.004039, 0.043396, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004114, 0.042910, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004264, 0.041942, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004486, 0.040503, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004772, 0.038610, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.005089, 0.036287, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.005463, 0.033555, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.005890, 0.030446, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.006349, 0.026993, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.006831, 0.023237, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.007312, 0.019219, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.007761, 0.014986, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008146, 0.010586, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008438, 0.006071, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008607, 0.001493, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008629, -0.003097, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008481, -0.007646, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.008146, -0.012103, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.007620, -0.016417, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.006922, -0.020544, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.006081, -0.024439, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.005130, -0.028062, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004109, -0.031376, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.002965, -0.034340, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.001854, -0.036933, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.000701, -0.039120, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.000447, -0.040879, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.001485, -0.042200, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.002445, -0.043065, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.004039, -0.043396, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.004603, -0.042864, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005225, -0.041852, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005591, -0.040400, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005890, -0.038506, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.006100, -0.036193, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.006209, -0.033486, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.006230, -0.030414, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.006160, -0.027011, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005995, -0.023315, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005720, -0.019367, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.005326, -0.015212, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.004796, -0.010898, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.004126, -0.006473, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.003336, -0.001984, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.002456, 0.002523, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.001522, 0.006998, 0.360711)
boolstatus = Part.InsertCurveFilePoint(-0.000570, 0.011398, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.000366, 0.015674, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.001249, 0.019783, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.002046, 0.023682, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.002732, 0.027330, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.003300, 0.030687, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.003716, 0.033718, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.003984, 0.036390, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004172, 0.038666, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004141, 0.040535, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004091, 0.041958, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004056, 0.042915, 0.360711)
boolstatus = Part.InsertCurveFilePoint(0.004045, 0.043395, 0.360711)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane9 As Object
Set myRefPlane9 = Part.FeatureManager.InsertRefPlane(8, 0.360711, 0, 0, 0, 0)
myRefPlane9.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

Sub main10()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Dim COSMOSWORKSObj As Object
Dim CWAddinCallBackObj As Object
Set CWAddinCallBackObj = swApp.GetAddInObject("CosmosWorks.CosmosWorks")
Set COSMOSWORKSObj = CWAddinCallBackObj.COSMOSWORKS
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.003669, 0.041940, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003744, 0.041470, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003894, 0.040536, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004116, 0.039148, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004402, 0.037321, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004722, 0.035078, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005097, 0.032442, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005526, 0.029441, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005989, 0.026108, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006474, 0.022482, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006960, 0.018603, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007416, 0.014517, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007812, 0.010269, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008118, 0.005910, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008306, 0.001488, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008352, -0.002945, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.008233, -0.007340, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007933, -0.011647, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.007449, -0.015817, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006796, -0.019807, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.006005, -0.023574, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.005105, -0.027079, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.004137, -0.030286, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003048, -0.033155, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.001989, -0.035666, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.000887, -0.037784, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.000212, -0.039489, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.001208, -0.040771, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.002131, -0.041611, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.003669, -0.041940, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.004217, -0.041429, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.004823, -0.040455, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005184, -0.039054, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005483, -0.037227, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005698, -0.034993, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005818, -0.032379, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005854, -0.029412, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005806, -0.026124, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005666, -0.022553, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005422, -0.018738, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.005063, -0.014723, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.004575, -0.010553, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.003951, -0.006274, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.003211, -0.001934, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.002386, 0.002424, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.001507, 0.006752, 0.395800)
boolstatus = Part.InsertCurveFilePoint(-0.000611, 0.011006, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.000269, 0.015142, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.001101, 0.019116, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.001849, 0.022887, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.002493, 0.026414, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003023, 0.029659, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003409, 0.032590, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003654, 0.035172, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003823, 0.037372, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003783, 0.039177, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003726, 0.040551, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003688, 0.041475, 0.395800)
boolstatus = Part.InsertCurveFilePoint(0.003674, 0.041939, 0.395800)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Dim myRefPlane10 As Object
Set myRefPlane10 = Part.FeatureManager.InsertRefPlane(8, 0.395800, 0, 0, 0, 0)
myRefPlane10.Select2 True, 1
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True


Set CWAddinCallBackObj = Nothing
Set COSMOSWORKSObj = Nothing
End Sub

